/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";
import { useEffect, useState } from "react";
import { SearchBook } from "./search";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import dynamic from 'next/dynamic'
import { isEmpty } from "lodash";

const SelectOption = dynamic(() => import('react-select'), { ssr: false })

const catagories = ["Bisnis", "Buku Anak", "Buku Pelajaran", "Buku Referensi", "Buku UKOM", "Ekonomi", "Kesehatan", "Komik", "Novel", "Pengembangan Diri", "Sastra", "Sejarah"];
const authors = [
    "A. Nurlaela Amin, S.Kep., Ns., M.Kes.",
    "AASP. Chandra dewi, SKM., M.Kes.",
    "Abiwardani Sekarningrum, A.Md.Gz.",
    "Ach. Arfan Adinata, S.Kep., Ns., M.Kep.",
    "Achmad Rizki Azhari, S.KM., MKM",
    "Achmad Rizki Azhari, SKM., MKM",
    "Achmad Rizki Azhari, SKM., MKM.",
    "Ade Irma Suryani, S.Farm., M.Farm.",
    "Ade Krisna Ginting, SST., M.Kes.",
    "Ade Ubaidah, M.Psi., Psikolog.",
    "Ade Zakiya Tasman Munaf, S.T.Keb., M.Keb",
    "Adriana Bangun. SST., MKM.",
    "Afina Muharani Syaftriani, S.Kep., Ns., M.Kep.",
    "Afriyana Siregar, S.Gz., M.Biomed.",
    "Agnes Erida Wijayanti, S.Kep., Ns., M.Kep.",
    "Agnes Ratna Saputri, S.Tr.Keb., MARS",
    "Agus Hendra Al Rahmad, SKM, MPH.",
    "Agus Hendra Al Rahmad, SKM., MPH.",
    "Agus Purnama Sari, SST., M.Keb.",
    "Agus Riyanto, S.Kep., Ns.",
    "Agusliani, S.Tr.Keb., M.Keb",
    "Ahmad Guntur Alfianto, S.Kep., Ns., M.Kep.",
    "Ahmad Wasis Setyadi, S.Kep., Ns., M.Si., MPH",
    "Ahmad Yani, S.Gz., M.KM., RD",
    "Ahmad Yani, S.Gz., M.KM., RD.",
    "Ai Kustiani, S.Gz., M.Si.",
    "Aida Ratna Wijayanti, S.Keb., Bd., M.Keb.",
    "Aisyah Nur Azizah, S.Tr.Kep., M.Tr.Kep.",
    "Ajeng Novita Sari, S.SiT., M.Kes.",
    "Al Rivan Marsyah Dzikri, S.T., M.T.",
    "Alfian Abdul Rajab, S.Tr.Gz., M.Gz",
    "Alfika Awatiszahro., SST., Bd., M.Tr.Keb",
    "Alina Hizni, SKM., MPH.",
    "Alkausyari Aziz, SKM., M.Kes.",
    "Amanda Via Maulinda, S.Tr.Keb., M.K.M",
    "Ana Fadilah, S.Kep., Ns., M.Kep.",
    "Ana Fadilah, S.Kep.,Ns.,M.Kep",
    "Ana Lestari, S.ST., M.Kes",
    "Ana Puji Astuti, S.Kep., Ns., M.Kes.",
    "Anak Agung Ayu Mirah Adi, SKM., M.Kes.",
    "Andi Nurpati Panaungi, S.Si., M.Si., Apt.",
    "Angela Librianty Thome, S.Kep., Ners., M.Kep.",
    "Anggia Astuti, S.Kp., Ners., M.Kep",
    "Anin Wijayanti, S.Kep., Ns., M.Kes",
    "Anis Rosyiatul Husna.,S.Kep.Ns.,M.Kes",
    "Anita Shinta Kusuma, S.Kep., Ns., MAN",
    "Anita Shinta Kusuma, S.Kep., Ns., MAN.",
    "Annisa Febriana, S.Kep., Ns., M.Kep., Sp.Kep.Kom.",
    "Anugerah Humairah Z. S.Gz., M.Kes",
    "Apri Nur Wulandari, S.Kep., Ns., M.Kep",
    "apt Rachmawati Felani Djuria., S. Farm., MPH.",
    "apt. A. A. Pradnya Paramitha Vidiani, M.Farm.",
    "apt. Anifatus Sa’adah, M.Farm.",
    "apt. Anisa Devi Kharisma Wibowo, M.Farm.",
    "apt. Arifani Siswidiasari, M. Farm",
    "apt. Arifani Siswidiasari, S.Farm., M.Farm",
    "apt. Berwi Fazri Pamudi, S.Farm., M.Si(Han).",
    "apt. Chairunnisa, S.Farm., M.Farm.Klin",
    "apt. Clara Ritawany Sinaga, M.Farm.",
    "apt. Dwi Kurnia Putri, S.Farm., M.Si.",
    "apt. Gandes Winarni, M. Farm.",
    "apt. Hasma, S.Farm., M.Si.",
    "apt. Helman Kurniadi, S.Farm., M.Farm",
    "apt. Iwan Saka Nugraha, S.Farm., M.Kes",
    "apt. Krisna Dewi, M.Si.",
    "apt. M. Henityo Agung As'adi, M.Farm",
    "apt. Masita Sari Dewi, S.Farm., M.Farm.",
    "apt. Muh Taufiqurrahman, M.Farm.",
    "apt. Nadroh Br Sitepu, M.Si.",
    "apt. Novycha Auliafendri, S.Farm., M.Si.",
    "apt. Nurul Dahlia Harahap, S. Farm., M.Si.",
    "apt. Rachmawati Felani Djuria, S.Farm., MPH",
    "apt. Rachmawati Felani Djuria, S.Farm., MPH.",
    "apt. Rahmadani, S. Farm., M. Farm",
    "apt. Rahmadani, S.Farm., M.Farm",
    "apt. Rifqi Ferry Balfas, M.Farm.",
    "apt. Rika Puspita Sari, S. Farm., M.Si.",
    "apt. Salmah Handayani Lubis, S.Farm., M.Si",
    "apt. Sulasmi, S.Farm., M.K.M., M.Farm.",
    "apt. Tri Danang Kurniawan, S.Si., M.Farm.",
    "Apt. Tri Fitri Yana Utami, S.Farm., M.Sc",
    "apt. Valentina Girsang, M.Farm.",
    "apt. Wahyuni Watora, M.Farm.",
    "apt. Widhi Astutik, M.Farm",
    "apt. Widhi Astutik, S.Si., M.Farm",
    "apt. Wiska Mailisa, S.Farm., M.S.Farm.",
    "apt. Yetti Hariningsih, M.Farm.",
    "apt. Yusnita Usman, S.Si., M.Si.",
    "Arie Anggraini, S.ST., Bdn., M.Tr.Keb",
    "Arief Wahyudi Jadmiko",
    "Armi Mawaddah, S.Kep., Ners., M.Kep",
    "Asih Purwandari Wahyoe Puspita, S.Kep., Ners., M.Kep.",
    "Asima Lamtiar Hotnauli Pakpahan, S.Tr.Keb., M.Keb",
    "Asmaurika Pramuwidya, S.S.T., M.Kes.",
    "Asni Hasaini, S.Kep., Ns., M.Kep",
    "Asridawati Akib, S.ST., M.Keb.",
    "Assoc. Prof. Henny Syapitri, S.Kep., Ns., M.Kep., Ph.D",
    "Atnesia Ajeng, SST., Bd., M.Kes.",
    "Aulia Amini, SST., M.Keb.",
    "Awaliyah Muslimah Suwetty, S.Kep., Ns., M.Kep",
    "Ayu Azhari, SKM., M.Kes.",
    "Ayu Bulan Febry Kurnia Dewi, SKM., MM.",
    "Ayu Kurnia Anggraeni, SST., M.Keb.",
    "Baiq Dewi Sukma Septiani, M.Gz.",
    "Balbina Antonelda Marled Wawo, Ns., M.Kep., Sp.Kep.J",
    "Bd. Ani Triana, SST, M.Kes.",
    "Bd. Aprilita Br Sitepu, SST., M.K.M.",
    "Bd. Ardiyanti Hidayah, SST., M.Kes.",
    "Bd. Brivian Florentis Yustanta, SST, M.Kes",
    "Bd. Brivian Florentis Yustanta, SST., M.Kes.",
    "Bd. Desriati Sinaga, SST., M.Keb.",
    "Bd. Dwi Retno Wati, S.Tr Keb., M.Tr.Keb",
    "Bd. Dwi Retno Wati, S.Tr. Keb., M.Tr. Keb.",
    "Bd. Dwi Retno Wati, S.Tr.Keb., M.Tr.Keb.",
    "Bd. Erlina Hayati, SST., M.Kes.",
    "Bd. Ermawaty Arisandi Siallagan, SST., M.Kes.",
    "Bd. Ermawaty Arisandi Siallagan, SST.,M.Kes.",
    "Bd. Erni Hernawati, S.S.T., M.Keb., M.M., Ph.D.",
    "Bd. Erni Hernawati, SST., M.Keb., MM., Ph.D.",
    "Bd. Fitria Hikmatul Ulya, S.S.T., M.Tr.Keb.",
    "Bd. Ika Nur Saputri, SST., M.Keb.",
    "Bd. Ike Fitrah Atul Chabibah., S.ST., M.Kes., M.Keb.",
    "Bd. Iryani Yuni Yastutik, SST., M.Kes",
    "Bd. Merlina Sinabariba, SST., M.Kes.",
    "Bd. Nur Aliyah Rangkuti, S.Keb, M.KM",
    "Bd. Nurul Hidayati, SST., M.Tr.Keb.",
    "Bd. Peny Ariani, SST, M.Keb.",
    "Bd. Ratnawati Bancin, S.Keb., M.K.M.",
    "Bd. Retno Palupi Yonni Siwi, SST., M.Kes.",
    "Bd. Retno Wulan, S.S.T., Keb., M.K.M.",
    "Bd. Selvi Puspan Sari, SST., M.Tr.Keb",
    "Bd. Siti Nur Farida., SST., M. Kes",
    "Bd. Siti Nur Umariyah Febriyanti, S.Si.T., MH.",
    "Bd. Sri Wulan, S.ST., M.Tr.Keb.",
    "Bd. Sri Wulan, SST, M.Tr.Keb",
    "Bd. Vitrilina Hutabarat, SST., M.Keb.",
    "Bd. Yuliana, S.ST., M.Keb.",
    "Bd. Zaitun Hilwa, S.Tr.Keb., M.K.M",
    "Bdn, Yenny Aulya, SST., M.Keb.",
    "Bdn. Afritayeni, SST., M.Kes",
    "Bdn. Agriyaningsih Oktaviana H, S.Tr.Keb., M.Keb",
    "Bdn. Akma Listiana, SST., M.Kes.",
    "Bdn. Astin Nur Hanifah, SST., M.Kes.",
    "Bdn. Desi Br Sembiring, SST., M.Tr.Keb",
    "Bdn. Dewi Agustin, SST, MKM",
    "Bdn. Dyah Triwidiyantari, S.ST., M.Keb",
    "Bdn. Emi Br Barus, S.ST., M.Keb",
    "Bdn. Eny Siswati, SST., M.Si.",
    "Bdn. Evis Ritawani Hasibuan, SST., M.Kes.",
    "Bdn. Firdaus Mubayyina, S.Tr.Keb., M.Keb",
    "Bdn. Fitria Prabandari, SSiT., M.Keb",
    "Bdn. Helti Lestari Sitinjak, SST., M.Keb.",
    "Bdn. Heni Haryani, M.Keb.",
    "Bdn. Herliana, S ST., M.KM.",
    "Bdn. Hj. Zummatul Atika, SST., M.K.M.",
    "Bdn. Ika Warisantika, S.Tr.Keb., M.Keb.",
    "Bdn. Ike Fitrah Atul Chabibah, SST., M.Kes., M.Keb",
    "Bdn. Ike Fitrah Atul Chabibah., SST., M.Kes., M.Keb",
    "Bdn. Imelda Diana Marsilia, SST., SKM., M.Keb",
    "Bdn. Imelda Diana Marsilia, SST., SKM., M.Keb.",
    "Bdn. Intan Azkia Paramitha, S.Tr.Keb., M.Keb",
    "Bdn. Israini Suriati, S.ST.,M.Keb.,CBMHCT.",
    "Bdn. Kusumastuti, S.Si.T., M.Kes.",
    "Bdn. Leni Suhartini, S.ST., M.Kes.",
    "Bdn. Lia Fitria, SST., M.Keb.",
    "Bdn. Lilis Suryani, SST., M. Keb.",
    "Bdn. Meli Doloksaribu, S.Tr.Keb., M.Keb.",
    "Bdn. Ni Nyoman Ayuk Widiani, S.ST., M.Kes.",
    "Bdn. Ni Wayan Manik Parwati, S.Si.T., M.Keb.",
    "Bdn. Nisa Rizki Nurfita, S.ST., M.KM., CHTT.",
    "Bdn. Norma Jeepi Margiyanti, S.Si.T., M.Kes.",
    "Bdn. Novi Eniastina Jasa, S.ST., M.Kes.",
    "Bdn. Nurseha, S.ST., M.Keb.",
    "Bdn. Nurul Lidya, SST., M.Kes.",
    "Bdn. Pande Putu Indah Purnamayanthi, S.ST., M.Kes.",
    "Bdn. Rahma Kusuma Dewi, ST., SST., M.P.H",
    "Bdn. Ranny Septiani, SST., M.Keb",
    "Bdn. Rizki Amalia, SST., M.Kes",
    "Bdn. Sholikhah Eli Setiyani, S.Tr.Keb., M.Keb.",
    "Bdn. Siti Rochimatul Lailiyah, S.SiT., M.Kes",
    "Bdn. Sri Utami Subagio, M.Tr.Keb.",
    "Bdn. Warda Anil Masyayih, SST., M.Kes.",
    "Bdn. Wiwit Vitania, S.ST., M.Keb.",
    "Bdn. Woro Nurul Seftianingtyas, SST., M.Kes.",
    "Bdn. Yanti, S.SiT., M.Keb",
    "Bdn. Yaumil Fauziah, S.Tr.Keb., M.Keb.",
    "Bdn. Yulita Nengsih, S.SiT., M.Kes.",
    "Bdn.Rati Purwati, SST., M.Keb",
    "Bernadetta Germia Aridamayanti, S.Kep., Ns., M.Kep",
    "Bernadetta Germia Aridamayanti, S.Kep., Ns., M.Kep.",
    "Binarti Dwi Wahyuningsih, S.Kep., Ns., M.Kes.",
    "Bisepta Prayogi, S.Kep., Ns., M.Kep.",
    "Bq Safinatunnaja, S.Si.T., M.Keb",
    "Brivian Florentis Yustanta, SST., Bdn., M.Kes.",
    "Budi Antoro. S.Kep., Ns., M.Kep",
    "Budi Rahayu, S.ST., M.Keb.",
    "Bunga Mari Sembiring, S.Si., M.K.M.",
    "Cahaya Indah Lestari, SST., M.Keb.",
    "Cahyaning Setyo Hutomo, SST., M.Kes.",
    "Cemy Nur Fitria, S.Kep., Ns., M. Kep.",
    "Chaerunnimah, SKM, M.Kes",
    "Christina Yeni Kustanti, S.Kep., Ns., M.Nur., M.Pall.C., Ph.D",
    "Christina Yeni Kustanti, S.Kep., Ns., M.Nur., M.Pall.C., Ph.D.",
    "Christina Yeni Kustanti, S.Kep., Ns., M.Pall.C., Ph.D.",
    "Cindy Tri Utami",
    "Cynthia Puspariny, S.ST, Bdn., M.Kes.",
    "Cynthia Puspariny,S.ST., Bdn.,M.Kes.",
    "D. Eka Harsanto, S.Kp., M.Kes.",
    "Dadang Darmawan M.Kes",
    "Dani Mahmud, S.Pd., SST., MM.",
    "Daris Yolanda Sari, SST., Bdn., M.Keb",
    "Darmayanti, S. Kep., Ners., M.Kep",
    "Daryanto, SKP., M.Kep.",
    "Deasti Nurmaguphita, S.Kep., Ns., M.Kep., Sp.Kep.J",
    "Deasti Nurmaguphita, S.Kep.Ns., M.Kep., Sp.Kep.J.",
    "Deny Eka Widyastuti, SST., M.Kes., M.Keb",
    "Deny Eka Widyastuti, SST., M.Kes., M.Keb.",
    "Desi Rofita, S.ST.,M.Keb.",
    "Dessy Rindiyanti Harista, S.Kep., Ns., M.Kep",
    "Devi Harmita, S.Tr., Ners., M.Kep",
    "Devie Ismayanty, S.Psi., S.ST., Bdn., M.Tr.Keb.",
    "Dewi Ari Sasanti, S.ST., M.Kes",
    "Dewi Hanifah, M.Keb",
    "Dewi Nugraheni Restu Mastuti, S.KM., M.Gizi.",
    "Dewi Nur Anita, S.Tr.Keb., M.P.H.",
    "Dewi Nur Sukma Purqoti, S.Kep.,Ners., M.Kep.",
    "Dewi Sartika MS, S.Kep., Ns., M.Kes",
    "Dewi Yuliana.,S.Kep., Ns., M.Kep",
    "Dhea Natashia, S.Kep., Ns., M.S., PhD.",
    "Dhea Novita, M.Tr.Keb.",
    "Dhiah Dwi Kusumawati, S. ST., Bdn., MPH.",
    "Diah Miftahul Aini, M.Si.",
    "Dian Furwasyih, S.Keb., Bd.,MSc.",
    "Dian Samtyaningsih, SST., M.Kes.",
    "Diana Irawati, S.Kep., Ns., M.Kep., Sp.KMB.",
    "Dianita Primihastuti, S.ST., M.Keb",
    "Didi Taswidi S.Kep., Ners., M.Kep.",
    "Dily Ekasari, S.ST.Keb., M.K.M",
    "Dina Indarsita, SST., M.Kes.",
    "Dini Ariani, SST., M.Tr.Keb.",
    "Diniyah Kholidah, SST., S.Gz., MPH.",
    "Dita Humaeroh, S.SiT., Bdn., MKM., C.Herb",
    "Dita Wasthu Prasida ,SKM., M.Kes(Epid).",
    "Diyah Astuti Nurfa'izah, S.Kep., Ners., M.Kep",
    "Diyah Candra Anita, S.Kep., Ners., M.Sc.",
    "Diyah Sri Yuhandini, S.SiT, S.KM, M.Pd.",
    "Diyah Sri Yuhandini, S.SiT, SKM, MPd",
    "Diyanah Kumalasary, SST., M.Kes",
    "Domianus Namuwali, S.Kep., Ns., M.Kep.",
    "Dorce Sisfiani Sarimin",
    "Doris Noviani, S.ST., M.Keb.",
    "Dr Hardono S.Kep Ners M.Kep",
    "Dr Tita Rohita, S.Kep., Ners., MM., MKep",
    "Dr. Abdul Ghofur, SKp., M.Kes.",
    "Dr. Aemilianus Mau, S.Kep., Ns., M.Kep.",
    "Dr. Aemilianus Mau., S.Kep., Ns., M.Kep",
    "Dr. Agustina A. Seran, S.Si.T., MPH",
    "Dr. Aliana Dewi., SKp., MN",
    "Dr. Ana Pujianti Harahap, S.Si.T., M.Keb.",
    "Dr. Andi Parellangi, S.Kep, Ners., M.Kep., M.H.",
    "Dr. Ani Kristianingsih, S.ST., M.Kes.",
    "Dr. Apt. Dian Nurmawati, M.FARM., CRM., FACP",
    "Dr. apt. Oktariani Pramiastuti, M.Sc.",
    "Dr. apt. Sofia Rahmi, S. Farm., M.Si.",
    "Dr. Azizatul Hamidiyah, S.KM., M.Kes",
    "Dr. Bdn. Christina Pernatun Kismoyo, S.SiT., MPH",
    "Dr. Bdn. Nur Handayani, S.SiT, M.Kes",
    "Dr. Bdn. Subang Aini Nasution, M.Kes.",
    "Dr. Bdn. Tetty Rina Aritonang, S.ST., M.Keb",
    "Dr. Betty Suprspti SKp. MKes",
    "Dr. Betty Yosephin Simanjuntak, SKM., MKM.",
    "Dr. Christin Hiyana Tungga Dewi, SST., M.Kes",
    "Dr. Debora Paninsari, SST., Bdn., M.Keb",
    "Dr. Dona Martilova SST.M.Kes",
    "Dr. dr. Achdyat Premedi, MARS",
    "Dr. dr. Hany Puspita Aryani, M.M., M.Kes.",
    "Dr. Drs. Supriadi, S.Kp., M.Kep., Sp.Kom.",
    "Dr. Dwi Prihatin Era, S.Kp., M.Kep., SpMB.",
    "Dr. Dwi Prihatin Era, SKp., MKep., Sp.MB.",
    "Dr. Edy Soesanto, S.Kp., M.Kes.",
    "dr. Enty, MKK (K).",
    "Dr. Ethyca Sari , S.Kep.Ns., M.Kes.",
    "dr. Eva Hikmatul Damayanti, S.Ked.",
    "Dr. Eva Yuniritha, SST., M.Biomed.",
    "Dr. FAISAL IBNU, S.Pd., S.Kep.Ns., M.Kes.",
    "Dr. Faiza Yuniati, S.Pd., S.Kep., M.KM.",
    "Dr. Fenita Purnama Sari Indah, SKM., M.Kes.",
    "Dr. Fitriana, S.SiT., M.Kes.",
    "Dr. H. Andi parellangi., S.Kep., Ners., M.kep., M.H.",
    "Dr. Hardono, S.Kep., Ners., M.Kep",
    "Dr. Helena Pangaribuan, S.Kep., Ns., M.Kep.",
    "Dr. Herawati, S.Kep., Ns., M.Kep.",
    "Dr. Hermita Bus Umar, SKM., MKM",
    "Dr. Herta Masthalina, S.KM., M.PH.",
    "Dr. Hilmi Yumni, S.Kep., Ns., M.Kep., Sp.Mat",
    "Dr. Inggar Ratna Kusuma, MPH.",
    "Dr. Ir. Luki Mundiastuti, M.Kes.",
    "Dr. Ir. Rahayu Astuti, M.Kes.",
    "Dr. Irma Seriana, SST., M.Keb",
    "Dr. Irna Nursanti, M.Kep., Sp.Mat.",
    "Dr. Iskim Luthfa, S.Kep., Ns., M.kep.",
    "dr. Jacoba Nugrahaningtyas Wahjuning Utami, M. Kes.",
    "Dr. Jujuk Proboningsih, SKp., M.Kes.",
    "Dr. Juliet Tangka, S.Pd., M.Kes.",
    "Dr. Khotibul Umam, S.Kep., Ns., M.Kes",
    "Dr. La Jumu, S.Sos., S.Kep., Ns., MAP., MMKes",
    "Dr. Mia Srimiati, S.Gz., M.Si.",
    "Dr. Muh. Abdurrouf, S.Kep., Ns., M.Kep.",
    "Dr. Muhammad Hadi, M.Kep.",
    "Dr. Najah Soraya Nia, S.Sos., M.M.",
    "Dr. Neny Triana, S.Kep. Ns., M.Pd., M.Kep.",
    "Dr. Ni Luh Putu Inca Buntari Agustini, S.Kep., Ns., MNS.",
    "Dr. Ni Made Riasmini, S.Kp., M.Kes., Sp.Kom",
    "Dr. Ns. Chanif, MNS.",
    "Dr. Ns. Chanif, S.Kep., MNS.",
    "Dr. Ns. Dhiana Setyorini, M.Kep., Sp.Mat.",
    "Dr. Ns. Machmudah, M.Kep., Sp.Mat.",
    "Dr. Ns. Mamnuah, M.Kep. Sp.Kep.J.",
    "Dr. Ns. Sri Wahyuni, M.Kep., Sp.Kep.Mat",
    "Dr. Ns. Suhari., A.Per., Pen., MM",
    "Dr. Ns. Tri Ismu Pujiyanto, SKM., M.Kep., M.Kes",
    "Dr. Ns. Vivi Yosafianti Pohan, M.Kep.",
    "Dr. Nunuk Sri Purwanti, S.Kp., M.Kes.",
    "Dr. Nur Hidaayah, S.Kep., Ns., M.Kes.",
    "Dr. Nurma Afiani, S.Kep., Ns., M.Kep.",
    "Dr. Rahmad Gurusinga, S.Kep, Ns, M.Kep",
    "DR. Rika Yusnaini., S.Kep., Ns., M.Kes.",
    "Dr. Roma Sitio, S.Kep., M.Kep",
    "Dr. Sestu Retno Dwi Andayani, S.Kp., M.Kes",
    "Dr. Siang br Tarigan, S.Pd., S.Kep., M.Kes.",
    "Dr. Sri Handayani, S.Kep., Ns,.M.Kes",
    "Dr. Srinalesti Mahanani. S.Kep., Ns., M.Kep.",
    "Dr. Subang Aini Nasution, M.Kes.",
    "Dr. Surmiasih, S,Kep., Ners., M.Kes",
    "Dr. Susi Milwati, S.Kp.,M.Pd",
    "Dr. Ummu Muntamah, S.Kp., Ns., M.Kes",
    "Dr. Yeni Fitrianingsih, SST., Mkes",
    "Dr. Yuni Purwati, S.Kep., Ns., M.Kep.",
    "Dr. Yustiana Olfah, APP., M.Kes",
    "Dra. Sri Kusmiati, SKp., M.Kes",
    "Drg Arnetty M.Kes.",
    "Drg. Anses Warman, MM.",
    "drg. Ika Ifitri, MDSc.",
    "Drh. Ignatus Djuniarto, S.Kep., M.M.R.",
    "Dwi Apriyanti, M.Gz.",
    "Dwi Ardani Rochmaniah, SST., M.Keb",
    "Dwi Ayu Lestari, M.Gizi",
    "Dwi Susilowati, APPd, M.Kes.",
    "Dwi Susilowati, APPd., M.Kes.",
    "Dwining Handayani, S.Kep.Ns., M.Kes.",
    "Amrina nur rohmah, S.Tr.Keb., M.Keb",
    "Bd. Lidia Fitri, S.Keb, SKM, M.Kes",
    "Sahrir Ramadhan, M. Kep",
    "Yuni Kristiani Tumani, S.ST., M.Keb",
    "Baltasar Serilus Sanggu Dedu, S.Kep., M.Sc.",
    "Bdn. Dwi Sri Rahandayani, SST., M. Keb.",
    "Dr. Susi Milwati, S.Kp., M.Pd.",
    "Emy Yulianti, M.Kes.",
    "Heru Ginanjar Triyono, M.Kep., Ns.",
    "Mas Koko",
    "Ns. Arneliwati, M.Kep.",
    "Ns. Daniel Suranta Ginting, S.Kep, M.Kep.",
    "Ns. Eny Susyanti, S.Kep., M.Kep.",
    "Ns. Novita Amri, M.Kep.",
    "Ns. Shofi Khaqul Ilmy, S.Kep., M.Kep.",
    "Nur Fadhilah. M.Kes., Ph.D.",
    "Prof. Dr. Bdn. Zakkiyatus Zainiyah, M.Keb.",
    "Prof. Dr. Nilawati Uly, S.Si., Apt., M.Kes.",
    "Prof. Dr. Runjati, Bdn., M.Mid",
    "Prof. Dr. Runjati, Bdn., M.Mid.",
    "Sri Handayani, SPd., MKM.",
    "Eftyaningrum Dwi Wahyu Astutik, M.Tr.Keb.",
    "Eka Rahmawati, S.Tr.Keb., Bdn., M.Tr.Keb",
    "Eka Santi, S.Kep, Ns, M.Kep",
    "Eka Santi, S.Kep., Ns., M.Kep",
    "Ekki Noviana, M.Tr.Keb., Bd.",
    "Eko Sari Wahyuni, S.Kep., Ns., M.Kep.",
    "Elfrida Sianturi, S.Gz., M.Gz.",
    "Elisa Oktaviana, S.Kep., Ners., M.Kep",
    "Eliza Bestari Sinaga, SST, Bd., M.Kes.",
    "Elly Rustanti, S.Si., M.Sc.",
    "Elvie Rifke Rindengan, S.Si., M.Farm., Apt",
    "Emilda. AS., SST., MPH.",
    "Emilda.AS. SST., MPH.",
    "Endah Sri Wahyuni, S.Kep., Ns., M.Kep",
    "Endang Abdullah, S.Kp., M.Si.",
    "Endras Amirta Hanum, M.Tr.Keb.",
    "Endri Ekayamti, S.Kep.Ns., M.Kep.",
    "Enik Suhariyanti, S.Kep., Ners., M.Kep.",
    "Enny Virda Yuniarti, S.Kep., Ns., M.Kes",
    "Eriati, SST., MKM",
    "Erik Adik Putra Bambang Kurniawan, S.Kep., Ns., MSN",
    "Erma Puspita Sari, SST., Bdn., M.Kes.",
    "Erni Chaerani, S.Pd., S.Kep., MKM",
    "Ernik Rustiana, SST., M.Keb.",
    "Ernik Rustiana, STM.Keb",
    "Ernita Prima Noviyani, S.ST., Bdn., M.Kes",
    "Ernny Wally, S.Psi., M.KM.",
    "Erwin Purwanto, S.Kep., Ners., M.Kep",
    "Ester Radandima, S.Kep., Ns., M.Kep",
    "Ethic Palupi, S.Kep., Ns., MNS.",
    "Eva Oktaviani, M.Kep., Ns., Sp.Kep.An",
    "Evelina Maria Nahor, S.Pd., S.Si., M.Si., Apt",
    "Evi Yanti, SKM., M.Kes",
    "Evi Yanti, SKM., M.Kes.",
    "Evi Yanti,SKM., M.Kes.",
    "Evi Zahara, SST., M.Keb.",
    "Fadhila Azkiya, S.ST., M.Kes.",
    "Fadhilah, A.Md.Gz.",
    "Faisal Sangadji, S.Kep., Ns. M.Kep.",
    "Farida Utaminingtyas, S. ST., M. Keb.",
    "Fathimi, S.Kep., M.K.M",
    "Fatihah Wari Nurjanah, M.Tr.Keb.",
    "Fatimah, S.Kp., M.Kep., Ns., Sp.Kep.Kom.",
    "Febrina Dwi Nurcahyanti, SST.,MPH",
    "Febtian Cendradevi Nugroho., S.Kep., Ns., MSN",
    "Feling Polwandari, M.Keb.",
    "Feni Elda Fitri, S.Kep., Ns., M.Kep.",
    "Ferry Fadli Fratama, S.ST., M.Tr.Kep",
    "Fetty Rosyadia Wachdin, S.S.T Keb., MPH.",
    "Fika Nur Indriasari, S.Kep.,Ns.,M.Kep",
    "Fitri Ayatul Azlina, S.Kep., Ns, M.Kep.",
    "Fitria Gusfa, S.Si., M.Si.",
    "Fitria Jannatul Laili, S.Keb., Bd., M.M., M.Keb",
    "Fitria Yulanda",
    "Fitriana, S.Pd, M.Si.",
    "Frani Mariana, SST., M. Keb.",
    "Frani Mariana, SST., M.Keb.",
    "Friska Ernita Sitorus, S.Kep., Ns., M.Kep.",
    "Friska, S.Kep., Ns., M.Kep",
    "Friska, S.Kep., Ns., M.Kep.",
    "Fuji Istiana, S.Kep., Ns., M.Kep.",
    "Galuh Ismayanti, M.K.M.",
    "Ganda Ardiansyah, S.Kep.,Ns.,M.Kep",
    "Gempi Tri Sumini,SST., M.Kes.",
    "Gevi Melliya Sari, S. Kep., Ns., M.Kep.",
    "Gina Fazrina, S.Tr.Ftr., MKM.",
    "Gita Kostania, S.ST., M.Kes",
    "Gladeva yugi antari, S. SiT., M.Keb.",
    "Gusmadewi, AMd. Keb.SKM. M.Kes",
    "GUSMAN, SST, M.Kes",
    "H. Syahrul, SKM., M.Kes",
    "Habsyah Saparidah Agustina, S.Kep., Ners., M.Kep.",
    "Hadina, SST., M.Keb",
    "Hakim Tobroni HR., S.Kep., Ns., M.Tr.Kep.",
    "Hamdan Nur.S.Kep., Ns., M.Kes.",
    "Hana Nurhanifah Budiadi, SST., M.Tr.Keb",
    "Hanafi, S. Kep., M. Kep",
    "Hanafi, S.Kep., M.Kep",
    "Handayani, S.Kp., M.Kep., Sp.Mat.",
    "Hanifah Mardhotillah, S.Gz., M.Gz",
    "Hanik Khairun Nisa, S.Tr.Keb., M.Keb",
    "Hanim Nur Faiza, S.Kep., Ns., M.Kep",
    "Hanim Nur Faizah, S.Kep., Ns., M.Kep",
    "Hapisah,S.SiT.,M.PH",
    "Hardiningsih, SST., M.Kes.",
    "Harianti Fajar, S.Kep., Ns., M.Kes",
    "Harlyanti Muhma'innah Mashar, M.Sc.",
    "Hasanalita, S.SiT., M.Keb.",
    "Haswita, S.Kp., M.Kes",
    "Hatti Marlina Pakpahan, S.KM., S.Kep., NS., M.Kep.",
    "Hayun Manudyaning Susilo, SST., M.Keb",
    "Helmi Juwita, S.Kep., Ns., M.Kep",
    "Helmi Juwita, S.Kep., Ns., M.Kep.",
    "Helmi Rumbo, S.Kep., Ns., M.N.S",
    "Heni Frilasari, SST., Bd., M.Kes.",
    "Heni Setyowati, S.SiT., M.Kes",
    "Henny Purwandari, S.Kep., Ns., M.Kes.",
    "Heri Rosyati, SSiT., M.KM.",
    "Heri Tri Wibowo, SKM., SKep.Ns., M.Kes",
    "Heri Triwibowo, SKM., SKep., Ns., M.Kes",
    "Herlina, S.Kep., Ns., M.Kes",
    "Herlinawati, M.Kes.",
    "Herma Yesti, S.ST, M.Keb.",
    "Hernita Frisnawati Purba, S.Kep., M.Kep.",
    "Herrywati Tambunan, S.Tr.Keb., MKM.",
    "Hetti Marlina Pakpahan, SKM., S.Kep., Ns., M.Kep",
    "Hetty Gustina Simamora, SKM., M.Kes.",
    "Hidayati, S.K.M., M.K.M.",
    "Hildagardis Meliyani Erista Nai, S.KM., M.P.H.",
    "Hj. Badriah, SST., MPH",
    "Hotmarina Lumban Gaol, S.Kep., Ns., M.K.M.",
    "Husnul Khatimah, SKM., M.Kes.",
    "Hutari Puji Astuti, S.SiT., M.Kes., M.Keb",
    "I Gede Putu Darma Suyasa, S.Kp., M.Ng., Ph.D.",
    "I Wayan Ambartana, SKM., M.Fis.",
    "Ida Rosidawati, S,Kep., Ners., M.Kep",
    "Ida Sofiyanti, S.Si.T., M.Keb.",
    "Idawati Binti Ambohamsah, S.Kep., Ns., M.Kes.",
    "Idcha Kusma Ristanti, S.Tr.Gz., M.Gz.",
    "Ignasia Yunita Sari, S.Kep., Ns., M.Kep.",
    "Iin Ira Kartika, SKM., MKM",
    "Iin Tri Marlinawati, S.Tr.Keb., MPH., M.Keb.",
    "Ika Puspa Windardi, S.Gz., M.Si.",
    "Ikawati setyaningrum, M.Kep",
    "Ike Nurjana Tamrin S.Kep,Ns.M.Kep.",
    "Ike Putri Setyatama, S.ST., M.Kes.",
    "Imam Tri Harsoyo, S.Pd, M.Si.",
    "Imran Yaman S Kep Ns M.Kes.",
    "Indah Kusmindarti, SST., Bd., M.Kes.",
    "Indah Mauludiyah, SST., MPH",
    "Indayana Setiawati, S.ST.,M.Kes",
    "Indra Domili, SKM, M.Kes.",
    "Indra Yulianti, SST., Bd., M.Kes",
    "Indrayanti, S.Kep., Ns., M.Kep., Sp.Kep.Kom",
    "Innani Wildania Husna, S.Kep., Ns., M.Kep.",
    "Intim Cahyono, S,Kep., Ns. M.Kes.",
    "Ir. Abdul Hadi, MP.",
    "Irma, SKM.,M.Kes",
    "Isfaizah, S.Si.T., MPH.",
    "Isna Ovari, SKp., M.Kep",
    "Istiada Fatmawati, SST., M.Kes",
    "Istichomah, S.Kep., Ns., M.Kes.",
    "Iswanto Gobel, S.Kep., Ns., M.Kep.",
    "Iva Milia Hani Rahmawati, S.Kep., Ns., M.Kep",
    "Ivana Devitasari, SST., M.Tr.Keb",
    "Iwan Tri Bowo",
    "Jovie Mien Dumanauw, S..Si., Apt., M.Sc.",
    "Joyo Minardo, S.Kp., Ns., M.Kes.",
    "Juanda Syafitasari, M.Keb",
    "Juanda Syafitasari, SST., M.Keb.",
    "Jum Natosba, M.Kep., Ns., Sp.Kep.Mat.",
    "Jumaedi, SKM., MM",
    "Junaidi, SST, M.Kes.",
    "Juni Purnamasari, Ners., M.Kep.",
    "Kadek Novi Andani, S.Kep., Ns., M.N.Sc",
    "Kartinah, S.Kep., Ns., MPH.",
    "Katarina Iit, SST., M.Kes",
    "Keysha Yasmine Asshafira",
    "Khartini Kaluku, S.Gz., M.Kes.",
    "Khrispina Owa, SST., M.Kes.",
    "Khusana Rahma, S.Kep., M.Tr.Kep.",
    "Komala Sari, S.Kep., Ns., M.Kep",
    "Kunnati, S.ST., M.KM",
    "Kurniawati S.Kep., Ns., M.Kep",
    "Laela Febriana, S.Farm., M.Farm",
    "Laily Rachmawati, S.SiT., M.KM",
    "Lam Murni Br Sagala, S.Kep.,Ns.,M.Kep",
    "Lasria Simamora, SST., MKM",
    "Lasria Simamora, SST., MKM.",
    "Legia Prananto, Dipl.Rad., S.Pd., S.Ag., MM.",
    "Legina Anggraeni, SST., MKM",
    "Lely Khulafa'ur Rosidah, S.ST., M.Kes.",
    "Leni Agustin, S.Kep., Ners., M.Kep",
    "Leni Nurlinayanti, S.Farm., M.Farm.",
    "Lexy Oktora Wilda, S.Kep., Ns., M. Kep.",
    "Lia Agustin, S.ST., MPH.",
    "Lida Khalimatus Sa'diyah, SSiT., Bd., M.Kes",
    "Lidya Fransisca, SST., M.Kes.",
    "Lilia Faridatul Fauziah, S.Tr.Keb., M.Gz.",
    "Lilik Hanifah, SST., M.Kes., M.Keb.",
    "Lilis Zuniawati Setianingsih, S.ST., Bd., MH.Kes.",
    "Lin Tri Marlinawati, S.Tr. Keb., MPH., M.Keb",
    "Linda Widiastuti, S.Kep. Ns, M.Kep",
    "Linda Widiastuti, S.Kep., Ns., M.Kep.",
    "Liza Erviana, S.Tr.,M.Keb",
    "Luluk Handayani, S.Tr.Keb., M.Tr.Keb.",
    "Lutfi Wahyuni, S.Kep. Ns. M.Kes",
    "M.Keb.",
    "Machfudloh, S.SiT., MH.Kes., M.Keb.",
    "Marchatus Soleha, S.ST., M.Kes",
    "Margaretha Lelyana, Amkep., SKM., MKM.",
    "Maria Dolorosa P. Sogen, S.Gz., M.Gz",
    "Maria F Vinsensia D P Kewa Niron, SST., M.Kes.",
    "Maria Florentina Nining Kosad, SST., M.Kes",
    "Maria Kareri Hara, S.Kep.,Ns.,M.Kes.",
    "Mariyatul Qiftiyah, SST., M.Keb.",
    "Marmi, S.S., M.Kes",
    "Marmi, S.ST., M.Kes.",
    "Marwati, S.Tr.Keb., MKM.",
    "Maryadi, S.Kep., Ns., M.Kep",
    "Masdalis, SKM., M.Kes.",
    "Masdalis. SKM., M.Kes.",
    "Mastina, S.ST., M.Keb.",
    "Masturoh, S.ST., MPH",
    "Masyita Haerianti, S.Kep., Ns., M.Kep",
    "Maulidya Septiany, S.Kep., Ns., M.Kep.",
    "Maya Sukmayati, S.ST., M.KM.bdn.",
    "Megawati, S.ST., MKM",
    "Megayana Yessy Maretta, SST., M.Keb",
    "Megayana Yessy Maretta, SST., M.Keb.",
    "Meggy Wulandari Kai, S.Tr.Kep., M.Tr.Kep.",
    "Mei Rianita Elfrida Sinaga, S.Kep., Ns., M.Kep",
    "Mei Widyawati, S.Kep., Ns., M. Kep.",
    "Meli Diana, S.Kep., Ns., M.Kes.",
    "Merry Margaritha Verawaty Seu, SST.,M.Keb",
    "Mesya, S.Kep., Ns., M.Kep",
    "Meta Rosdiana, SST., M.Kes.",
    "Minarti, S.Kep., Ns., M.Kep. Sp.Kom.",
    "Mokhamad Nurhadi, S.Kep., Ns., M.Kep., MM.",
    "Muhammad Ardi, M.Kep., Ns., Sp.Kep.M.B.",
    "Muhammad Arif, M.K.M.",
    "Muhammad Bachtiar Safrudin, M.Kep., Sp.Kep.Kom.",
    "Muhammad Husaini, S.Kep., M.Kes",
    "Muhammad Qasim, S.Kep., Ns., M.Kes.",
    "Muhammad Syahid Hidayat BS., SH., S.Kep., MS., MH",
    "Mukhoirotin, S.Kep., Ns., M.Kep.",
    "Munifa, SKM., MPH.",
    "Murni Sari Dewi Simanullang, S.Kep., Ns., M.Kep",
    "Musviro, S.Kep., Ns., M.Kes",
    "Nadia Alfira, S.Kep., Ns., M.Kep.",
    "Nadiyah Kamilia S.KM., M.P.H",
    "Nahdiyah Karimah, M.Tr.Keb.",
    "Najihah, S.Kep., Ns., M.Kep.",
    "Namiroh Falah Hasibuan, S.Tr.Keb., MKM.",
    "Nana Fitriana, S.Tr.Keb., M.Kes.",
    "Nanda Yansih Putri, S.ST., M.Keb.",
    "Nanin Juliana, S.Kep., Ns., M.K.M",
    "Narmin, S. ST., M. Keb",
    "Nela Novita Sari,S.Tr.Keb., M.Keb",
    "Neni Nuraeni,M.Kep.,Ns.Sp.Kep.Mat",
    "Nety Mawarda Hatmanti, S.Kep., Ns., M.Kep.",
    "Ngatemi, S.Si.T, MKM.",
    "Ngatemi, S.Si.T., MKM",
    "Ni Ketut Sujati, S.St., M.Kes",
    "Ni Nengah Arini Murni, SST., M.Kes",
    "Ni Nengah Arini Murni, SST., M.Kes.",
    "Ni Wayan Sri Rahayuni, S.ST.,M.Kes.",
    "Ni'mah Mufidah, S.Kep., Ns., M.Kep",
    "Nikita Welandha Prasiwi, S.Tr.Keb., M.Gz.",
    "Nila Trisna Yulianti, S.SiT.,Bdn.,M.Keb",
    "Nima Eka Nur Rahmania, S.KM., M.KKK",
    "Nimsi Melati, S.Kep., Ns., MAN.",
    "Nina Rizka Rohmawati, S.Kep., Ns., M.Kep.",
    "Ninik Yunitri, S.Kep., Ns., M.Kep., Sp.Kep.J, Ph.D.",
    "Nor Eka Noviani, S.Gz., M. PH., Dietisien",
    "Norif Didik Nur Imanah, S.SiT., M.Kes.",
    "Norlaila Sofia, S.Si.T., M.Keb.",
    "Nova Avianti Rahayu, S.Tr.Keb., M.Keb",
    "Noveri Aisyaroh, S.SiT., M.Kes.",
    "Novi Puspita Sari S.Gz., M.Kes",
    "Novi Susanti, SST., M.Kes",
    "Novi Susanti., SST., M.Kes.",
    "Novia Faizatiwahida, S.Kep., Ns., M.N.Sc",
    "Novia Wulansari., S.Kep., Ners., M.Kep., Sp.Kep.MB.",
    "Novian Swasono Hadi, SST., M.P.H.",
    "Novida Prima Wijayanti, S.Kep., Ns., M.Kep.",
    "Ns Flora Sijabat, S.Kep., MNS.",
    "Ns. Aam Sumadi, SKep., MKep., FISQua",
    "Ns. Agus Dwi Pranata, M.Kep",
    "Ns. Aida Kusnaningsih, M.Kep., Sp.Kep.Mat",
    "Ns. Ainal Mardhiah, M.Kep.",
    "Ns. Amatus Yudi Ismanto, M.Kep., Sp.Kep.An., PhD.NS.",
    "Ns. Amatus Yudi Ismanto, Sp.Kep.An., PhD.NS",
    "Ns. Amatus Yudi Ismanto, Sp.Kep.An., PhD.NS.",
    "Ns. Anastasia Hardyati., M.Kep., Sp.KMB.FISQua",
    "Ns. Ari Susiani, M.Kep",
    "Ns. Arie Sulistiyawati, S.Kep., M.Kep.",
    "Ns. Arie Sulistiyawati., M.Kep",
    "Ns. Arie Sulistiyawati., S.Kep. M.Kep",
    "Ns. Arifin Hidayat, SST., M. Kes",
    "Ns. Asmiana Saputri Ilyas, S.Kep., M.Kes",
    "Ns. Asnani, S.Kep., M.Ked.",
    "Ns. Ayut Merdikawati, S.Kep., M.Kep.",
    "Ns. Azhar Mu'alim, M.Kep., CWCCA",
    "Ns. Chairil Anwar, S.Kep., M.Kep",
    "Ns. Chichi Hafifa Transyah, S.Kep, M.Kep",
    "Ns. Chinthia Kartikaningtias, M.Kep.",
    "Ns. Daniel Suranta Ginting, S.Kep., M.Kep",
    "Ns. Daniel Suranta Ginting, S.Kep., M.Kep.",
    "Ns. Deli Maria P, M.Kep., Sp.Kep.Kom.",
    "Ns. Delta Aprianti, S.Kep., M.Kep",
    "Ns. Dera Alfiyanti, M.Kep.",
    "Ns. Destria Efliani, S.Kep., MM.",
    "Ns. Dewi Anggraini, S.Kep., M.S.",
    "Ns. Dewi Anggraini., S.Kep., M.S.",
    "Ns. Dewi Fitriani, S.Kep., M.Kep",
    "Ns. Dewi Siyamti, S.Kep., M.Kep.",
    "Ns. Dewi Tiansa Barus, S.Kep., M.K.M.",
    "Ns. Dian Octavia, M.N.S",
    "Ns. Dian Ratna Elmaghfuroh, S.Kep., M.Kes.",
    "Ns. Diena Juliana, S.Kep., M.Kes.",
    "Ns. Diliani, M.Kep.",
    "Ns. Diyah Candra Anita, S.Kep., M.Sc.",
    "Ns. Dodik Hartono, S.Kep., M.Tr.Kep",
    "Ns. Dodik Hartono, S.Kep., M.Tr.Kep.",
    "Ns. Dudella Desnani Firman Yasin, S.Kep., M.Kep.",
    "Ns. Dwi Astuti, S.Kep., M.Kep.",
    "Ns. Dwi Christina Rahayuningrum, M.Kep",
    "Ns. Dwi Suryani, S.Kep., M.Kep",
    "Ns. Eka Puji Hastuti, S.Kep.",
    "Ns. Eliza, S. Pd., S. Kep., M. Kep.",
    "Ns. Emitrafatriona, M.Kep.",
    "Ns. Endang Fauziyah Susilawati, M.Kep",
    "Ns. Eni Kusyati, M.Si.Med",
    "Ns. Eny Susyanti, S.Kep., M.Kep",
    "Ns. Eny Susyanti, S.Keр., М.Kep.",
    "Ns. Erik Kusuma, S.Kep., M.Kes.",
    "Ns. Ernawati Hatuwe, S.Kep., M.Kep",
    "Ns. Estefina Makausi, S.Kep., MMKes., CHAE.",
    "Ns. Evodius Nasus, S.Kep., M.E.",
    "Ns. Farah Luqyana, M.Kep.",
    "Ns. Faridah Aini, M.Kep., Sp.KMB",
    "Ns. Faridah Aini, S.Kep., M.Kep., Sp.KMB",
    "Ns. Firmina Theresia Kora, S.Kep., M.P.H.",
    "Ns. Fitra Mayenti, S. Kep., M.Kep.",
    "Ns. Fitria Nola Rezkiki, S.Kep., M.Kep.",
    "Ns. Fitrio Deviantony, S.Kep., M.Kep.",
    "Ns. Fransiska Aloysia Mukin, M.Kep",
    "Ns. Fransiska Aloysia Mukin, M.Kep.",
    "Ns. Hairunnisa, S.Kep., M.Kep",
    "Ns. Handi Rustandi, S.Kep., MAN",
    "Ns. Hardin, S.Kep., M.Kep.",
    "Ns. Harmilah, S.Pd., S.Kep, M.Kep., Sp.KMB.",
    "Ns. Harmilah, S.Pd., S.Kep., M.Kep., Sp.KMB.",
    "Ns. Hasian Leniwita, M. Kep., Sp. Kep. MB",
    "Ns. Hesti Ratna Sari, M.Kep.",
    "Ns. Hesty, S.Kep.,M.Kes.",
    "Ns. Hirdes Harlan Yuanto, M.Tr.Kep.",
    "Ns. I Gusti Ayu Putu Desy Rohana, M.Kep., Sp.Kep.Kom",
    "Ns. Iba Supra Saba, M.Kep.",
    "Ns. Ida Rosidawati, S.Kep., M.Kep.",
    "Ns. Ida Zuhroidah, S.Kep.,M.Kes.",
    "Ns. Idriani., M.Kep., Sp.Mat.",
    "Ns. Imelda Rahmayunia Kartika, S.Kep., M.Kep.",
    "Ns. Indana Lazulfa, S.Kep., M.Kep.",
    "Ns. Indra Tri Astuti, M.Kep., Sp.Kep.An",
    "Ns. Irhamdi Achmad, S.Kep.,M.Kep",
    "Ns. Jagentar Parlindungan Pane, S.Kep., M.Kep.",
    "Ns. Jelita Siska Herlina Hinonaung, S.Kep., M.Kep",
    "Ns. Jeni Oktavia Karundeng, M.Kep, Sp.Kep.A.",
    "Ns. Juli Widiyanto, S.Kep., M.Kes(Epid).",
    "Ns. Juli Widiyanto., S.Kep., M.Kes.Epid",
    "Ns. Jumari, S.Kep., M.Kep., Sp.Kep.MB",
    "Ns. Kartika Wijayanti, M. Kep.",
    "Ns. Kartika Wijayanti, M.Kep",
    "Ns. Kartini K Rahantoknam, M.Kep.",
    "Ns. Leni Wijaya, S.Kep., M.Kes.",
    "Ns. Lisa Rizky Amalia, S.Kep., M.Kep.",
    "Ns. Liza Puspa Dewi, S.Kep., M.Kep",
    "Ns. Loritta Yemina., M.Kep., Sp.Kep.M.B",
    "Ns. Ludovikus Duhu, M.Kep",
    "Ns. Lydia Moji Lautanm, M.Kep.",
    "Ns. M.Yamin, S.Kep., SKM., M.Kes",
    "Ns. Maryana, M.Kep",
    "Ns. Maryono, S.Kep, M.Kes.",
    "Ns. Maulin Halimatunnisa', M.Kep",
    "Ns. Mila Triana Sari, M.Kep.",
    "Ns. Mimi Rosiska, M.Kep",
    "Ns. Mimi Rosiska, S.Kep., M.Kep",
    "Ns. Moza Suzana, M.Kep",
    "Ns. Muanngsih, M.Kep., Sp.Kep.Mat.",
    "Ns. Muh Zukri Malik, M.Kep.",
    "Ns. Muhammad Khoirul Amin, M.Kep., Sp.Kep.J.",
    "Ns. Mutianingsih, M.Kep",
    "Ns. Nevi Kuspiana Lesmana, M.Kep.",
    "Ns. Ni Luh Kompyang Sulisnadewi, M.Kep., Sp.Kep.An.",
    "Ns. Ni Luh Putu Suardini Yudhawati, M.Kes., M.Kep.",
    "Ns. Ni Luh Seri Astuti, S.Kep., M.Kep.",
    "Ns. Nida Laila, S.Kep.",
    "Ns. Nina Sunarti, M.Kep.",
    "Ns. Nita Theresia, S.Kep., M.Kes",
    "Ns. Nofrida Saswati, M.Kep.",
    "Ns. Novia Wulansari., M.Kep., Sp.Kep.MB",
    "Ns. Novita Amri, M.Kep",
    "Ns. Novita Sari, S.Kep., M.Kep.",
    "Ns. Nuniek Setyo Wardani, S.Kep., M.Kep.",
    "Ns. Nur Eni Lestari, M.Kep., Sp.Kep.An.",
    "Ns. Nuraini, S. Kep., M. Kep",
    "Ns. Nurul Hidayah, S.Kep., MS.",
    "Ns. Nurul Purborini, MS, Ph.D.",
    "Ns. Nyoman Agus Jagat Raya, S.Kep., MNS",
    "Ns. Okti Rahayu Asih, S.Kep., M.Kep",
    "Ns. Oril Ardianto, S.Kep., M.Kep",
    "Ns. Ponirah, S.Kep., M.Kes.",
    "Ns. Prima Yoselina, S.Kep., M.Kep",
    "Ns. Primasari Mahardhika Rahmawati, S.Kep., M.Kep.",
    "Ns. Putri Halimu Husna, M.Kes.",
    "Ns. Putri Nilsari, S.Kep., M.Kep",
    "Ns. Ragil Supriyono, M.Kep.",
    "Ns. Ratna Aryani, M.Kep",
    "Ns. Revi Yulia., M.Kep.",
    "Ns. Revie Fitria N, S.Kep., M.Kep",
    "Ns. Rian Maulana Yusup, S.Kep., M.Kep",
    "Ns. Rina, S.Kep., M.Kep.",
    "Ns. Riris Friandi, M.Kep.",
    "Ns. Riris Risca Megawati, M.Kep",
    "Ns. Rizki Andriani, M.Kep.",
    "Ns. Rostiodertina Girsang, S.Kep., М.Kep.",
    "Ns. Ryka Widyaningtyas, S.Kep., M.Sc",
    "Ns. Safra Ria Kurniati, M.Kep.",
    "Ns. Sarti Oktarina Purba, S.Kep., M.Kep",
    "Ns. Sasteri Yuliyati, S.Kep., M.Kep.",
    "Ns. Sefrina Rukmawati, S.Kep., M.Kes.",
    "Ns. Sigit Priyanto, M.Kep",
    "Ns. Siska Mayang Sari, M.Kep",
    "Ns. Siska Mayang Sari, M.Kep.",
    "Ns. Siti Komariah, SKep., MARS., FISQua.",
    "Ns. Sri Hartini, S.Kep., M.Kes.",
    "Ns. Sri Hunun Widiastuti, M.Kep., Sp.Kep.J.",
    "Ns. Sri Laela, M.Kep., Sp.Kep.J.",
    "Ns. Sri Melfa Damanik, M.Kep., Sp.Kep.An",
    "Ns. Sri Wianti, S.Kep., M.Kep.",
    "Ns. Sri Yani, S.Kep., M.M.R.",
    "Ns. Sukri, S.Kep., M.Kep.",
    "Ns. Suryani Hartati, M.Kep., Sp.Kep.Mat.",
    "Ns. Susi Sri Noviyanti, S.Kep., MM",
    "Ns. Suwarningsih, SKep., MKep",
    "Ns. Syafrina Arbaani Djuria, S.Kep., M.Kep.",
    "Ns. Tanti Marjiana, S.Kep., M.Kep, FISQua., FIHFAA., FRSPH",
    "Ns. Tanti Marjiana, S.Kep., M.Kep., FISQua., FIHFAA., FRSPH.",
    "Ns. Tati Hidayati, S.Kep., M.Kep, FisQua.",
    "Ns. Tina Mawardika., M.Kep., Sp.Kep.Mat.",
    "Ns. Tri Susilo, S.Kep., M.Kep.",
    "Ns. Tri Wahyuni Ismoyowati., S.Kep., M.Kep.",
    "Ns. Tuti Herawati, S.Kep., M.Kep.",
    "Ns. Tuti Sahara S.Kep., M.Kep.",
    "Ns. Umi Aniroh, S.Kep., M.Kes.",
    "Ns. Wasis Widodo, M.Kep., Sp.Kep.MB.",
    "Ns. Wasis Widodo.,M.Kep., Sp.Kep.MB.",
    "Ns. Weni Mailita, S,Kep., M.Kep.",
    "Ns. Winda Yuniarsih, S.Kep., M.Kep., Sp.KepMB.",
    "Ns. Wiwik Sofiah, APP., M.Kep",
    "Ns. Yeni Kartika Sari, M.Kep",
    "Ns. Yenny, M.Kep.,Sp.Kep.MB",
    "Ns. Yetti Syafridawita, S.Kep., M.Kep., Sp.Kep.K",
    "Ns. Yetti Syafridawita, S.Kep., M.Kep., Sp.Kep.K.",
    "Ns. Yosep Andri Putra, M.Kep.",
    "Ns. Yuli Erlina, S.Kep., M.Kes",
    "Ns. Yuli Erlina, S.Kep., M.Kes.",
    "Ns. Yunida Turisna Octavia , SKM., S.Kep., M.KM.",
    "Ns. Yusrawati, S.Kep., M.Kes",
    "Ns. Yusrawati, S.Kep., M.Kes.",
    "Ns. Yuyun Setiyawati, S.Kep., M.Kep.",
    "Ns. Zakiyah, S.Kep., M.Kep., Sp.Kep.J",
    "Ns. Zulfikar Peluw, S.Kep., M.Kep.",
    "Ns.Danur Azissah Roesliana Sofais,SKep.MKes",
    "Ns.Eny Susyanti, S.Kep., M.Kep",
    "Ns.Eny Susyanti, S.Kep., M.Kep.",
    "Ns.Eny Susyanti,S.Kep.,M.Kep",
    "Ns.Fitriani Agustina, S.Kep., M.Sc",
    "Ns.Fitrio Deviantony,S.Kep.,M.Kep",
    "Ns.Meining Issuryanti,S.Kep.,M.Kep",
    "Ns.Netti, S.Kep., M.Pd., M.Kep.",
    "Ns.Nurul Hidayah,M.Kep",
    "Ns.Sri Wianti, S.Kep., M.Kep",
    "Ns.Umi Aniroh,S.Kep.,M.Kes",
    "Nugraheni Agustyaningsih, Ftr., M.Si.",
    "Nuniek Tri Wahyuni, S.Kep., Ns., M.Kep.",
    "Nunung Nursasih, S.Kep., Ners., M.Kep., Sp.Kep.MB.",
    "Nunung Sri Mulyani S.Gz, M.Biomed.",
    "Nunung Sri Mulyani, S.Gz., M. Biomed., Dietisien.",
    "Nur Afriyanti, M.Si",
    "Nur Aini Fatimah, S.Kom., M.Kes",
    "Nur Fadhilah",
    "Nur Fadhilah, M.Kes., Ph.D",
    "Nur Fadhilah, M.Kes., Ph.D.",
    "Nur Fadilah Bakri, S.Si., M.Si., Apt.",
    "Nur Furi Wulandari, S.ST., M.Kes.",
    "Nur Hasanah, SKM., M.Kes.",
    "Nur Hidayati, S.SiT., M.Kes",
    "Nur Insani, SST., Ners., M.Biomed.",
    "Nur Isnaini, SST., Ners., M.Biomed",
    "Nur Sophia Matin, S.Keb., Bd., M.Keb.",
    "Nur Yeti Syarifah S.Kep., Ns., M.Med., Ed.",
    "Nurbaety, S.SiT. M.K.M",
    "Nurbaiti, SKM., M.Kes.",
    "Nurfaidah, SKM., M.Kes.",
    "Nurhalisa Wibawa",
    "Nurhayati, SKM., MPH.",
    "Nuridha Fauziyah, S.Kep., Ners., M.Kep",
    "Nurlaili Ramli, S.SiT. MPH",
    "Nurlia Ikaningtyas, S.Kep., Ns., M.Kep., Sp.Kep.MB, Ph.D, NS.",
    "Nurulicha, S.ST.,M.Keb",
    "Nurulicha, SST.,M.Keb",
    "Nurwahita, S.Kep., Ns., M.Kes.",
    "Nurwilda Kaswi, S.Si., M.Kes.",
    "Odi L. Namangdjabar, SST., M.Pd.",
    "Ossie Happina Sari, S.Si.T., M. Kes.",
    "Patria Asda, S.Kep, Ns., M.P.H.",
    "Poppy Siska Putri, SST, M.Keb",
    "Prima Daniyati Kusuma, S.Kep.,Ns.,M.Kep",
    "Priscilla Jessica Pihahey. SKM., M.K.M",
    "Priyani Haryanti, S.Kep., Ns., M.Kep., Ph.D.",
    "Prof. Dr. M. Hasinuddin, S.Kep. Ns. M.Kep",
    "Prof. Dr. Masrukhi, M.Pd.",
    "Prof. Dr. Mufdlillah, S.SiT., M.Sc.",
    "Pundra Dara Avindharin, S.Tr.Gz, M.K.M.",
    "Puspita Mardika Sari, S.Gz., M.Biotech., Dietisien.",
    "Putra Adi Irawan, S.ST., M.Si.",
    "R Endro Sulistyono, S.Kep., Ns., M.Kep",
    "Rahayu Budi Utami, S.Kep., Ns., M.Kes.",
    "Rahmad Aswin Juliansyah, S.S.T., M.Kes",
    "Rahmadona, SST., Bdn., M.Keb.",
    "Ranny Septiani, SST., M.Keb.",
    "Rasi Rahagia, S.Kep., Ns., M.Kep",
    "Ratna Suminar, S.ST., M.Tr.Keb.",
    "Reni Hertini, S.Kep., Ners., M.Kep.",
    "Reni Puspitasari, S.Kep., Ns., MSN.",
    "Renita Afriza, SKM., M.Kes.",
    "Renny Wulan Apriliyasari, S.Kep., Ns., M.Kep., Ph.D",
    "Resa Livia Nica, S.Kep., Ns., M.Kes.",
    "Reski Pebriani, S.Gz., M.K.M",
    "Resta Betaliani Wirata, S.Kep., Ns., MSN",
    "Retno Ayu Yuliastuti, S.Kep., Ns., M.Tr.Kep.",
    "Retno Puji Astuti, S. Kep., Ns., M.Kep.",
    "Ria Tri Harini Dwi Rusiawati, S.ST., M.Pd.",
    "Riadini Wahyu Utami, SST., MPH.",
    "Rian Anggia Destiawan, S.KH., M.Imun.",
    "Ribkha Itha Idhayanti, M.Kes.",
    "Rif'atul Amini, S.Gz., M.Gz.",
    "Rifda Nur Achriyana Arif, S.Kep., Ns., M.Kep",
    "Rifda Nur Achriyana Arif, S.Kep., Ns., M.Kep.",
    "Rigoan Malawat, S.Kep., M.Kes",
    "Rigoan Malawat. S.Kep., M.Kes",
    "Rilyn Novita Maramis, S.Pd., S.Si., M.Si., Apt.",
    "Rina Afrina, S.Kep., Ners., M.KM",
    "Rina Octavia, S.ST,. Bd,. M.Kes",
    "Rina Octavia, S.ST,. Bd,. M.Kes.",
    "Rina Utami, M.Tr.Keb.",
    "Rina Veronica, SKM., MKM",
    "Rina, SST., M.Tr.Keb",
    "Rini Gustina Sari, SST., M.Kes",
    "Rini Mustikasari Kurnia Pratama, S.Si.T., M.Keb",
    "Ririn Ratnasari, SST., M.Kes",
    "Risa Nurhayati, S.Kep., Ns., M.Kes.",
    "Riski Akbarani, S.KM., M.Kes.",
    "Risna Nurlia, S.ST., S.KM., M.KM.",
    "Ristiani, S.Tr.Keb., M.Keb.",
    "Rita Ariesta, M.Kes",
    "Rita Kirana, S.Pd., M.Kes",
    "Riyan Dwi Prasetyawan, S.Kep., Ns., M.Kep",
    "Rizeki Dwi Fibriansari, S.Kep., Ners., M. Kep.",
    "Rizeki Dwi Fibriansari, S.Kep., Ners., M.Kep",
    "Rizky Meuthia Pratiwi, S.Kep. Ns. M.Kep",
    "Rizzatul Khumairoh, SST., M.Keb.",
    "Rochmanita Sandya Afindaningrum, S.Tr.Keb., M.Keb.",
    "Rolita Efriani, S.ST., M.Keb.",
    "Rolly Harvie Stevan Rondonuwu M.Kep., Ns., Sp.Kmb",
    "Rona Riasma Oktobriariani, SST., M.Keb.",
    "Rosi Novita, SP., M.Kes.",
    "Roswita Victoria Rambu Roku, S.Kep, Ns, MSN",
    "Rully Fatriani, S. ST., M.Keb., CMBC.",
    "Rusiana Sri Haryanti, SST., MPH.",
    "Rusmilawaty, SKM., M.PH",
    "Saleha Salihun, S.Tr.Kes., M.Biomed",
    "Sally Yustinawati Suryatna, S.Kep., Ners., M.Kep",
    "Saman, S.Kep., Ns., M.Kep",
    "Santi Wahyuni, S.Kp., M.Kep., Sp.Mat.",
    "Santi Wahyuni, SKp., M.Kep., Sp.Mat",
    "Sartika, S.Kep., Ns., M.Kep., Sp.Kep.K",
    "Sarwoko, S.Ag., S.Kep., Ns., M.Kes., M.Kep.",
    "Selpyani Sinulingga, SST., M.Kes.",
    "Septa Dwi Insani, S.Keb., Bd., MMRS",
    "Septian Andriyani, S.Kp., M.Kep",
    "Septiwiyarsi, SST., M.Kes.",
    "Serlina Silalahi, SST., M.Gz.",
    "Setyo Retno Wulandari, S.SiT., Bdn., M.Kes",
    "Shelly Festilia Agusanty, S.Gz, MPH",
    "Sherli mariance sari, S.Kep., Ners,. M.Kes.",
    "Sherly Angellina, S.SiT., M.Keb",
    "Shinta Maharani, Ns., M.Kep.",
    "Sholichin, SP, MT",
    "Sholichin, SP., MT.",
    "Sih Ageng Lumadi, S.Kep., Ns., M.Kep",
    "Silviatul Amalia, S.Keb., Bdn., M.Keb.",
    "Siti Aminah, SST., S.Pd., Bd., M.Kes",
    "Siti Fithrotul Umami, SST.,M.Kes",
    "Siti Khoiriyah, M.Kep",
    "Siti Komariyah, S.SiT., M.Kes.",
    "Siti maryam, S.ST., MPH.",
    "Siti R K Baderan, S.Gz., M.Kes",
    "Siti Rofi'ah, S.ST, M.Kes, Bdn.",
    "Siti Solihat Holida S.Kp., MM",
    "Siti Solihat Holida. S.Kp., MM.",
    "Sitti Herliyanti Rambu, S.Kep., Ns., M.Kes",
    "Slamet Wardoyo, SST., M. Kes.",
    "Sodikin, M.Kep., Ns., Sp.Kep.MB",
    "Sofyawati D.Talibo, SKM, M.Kes",
    "Sondang Tio Helena Manurung, S.Kp., M.Kep",
    "Sri Astutik Andayani, S.Kep., Ns, M.Kes.",
    "Sri Handayani Gurning, S.Farm., M.Farm., apt.",
    "Sri Handayani, S.Pd., MKM.",
    "Sri Hartini, S.Kep., Ns., M.Kes.",
    "Sri Ilawati., SST., M.Kes",
    "Sri Ilawati., SST., M.Kes.",
    "Sri Ilawati.,SST., M.Kes",
    "Sri Mulyani, M.Kes.",
    "Sri Raudhati, S.SiT., M.K.M.",
    "Sri Rusmini, S.Kep, Ners, M.Kep, MM., FISQua.",
    "Sri Rusmini, S.Kep., Ners., M.Kep., MM., FISQua",
    "Sri Setiasih, S.Si.T., Bdn., M.Kes.",
    "Sri Wahyuni, S.Si., M.Biomed.",
    "Stefania Efenhilda Tefa, S.Kep., Ns., M.Kep.",
    "Subandiyo, S.Pd., S.Kep., Ns., M.Kes",
    "Subandiyo, S.Pd., S.Kep., Ns., M.Kes.",
    "Suci Gustia Saputri, STr.Keb., MPH",
    "Sujianti, S.ST., M.Kes",
    "Sukmawati, S.Si.T., M.Kes.",
    "Sulastri, S.Kp., M.Kep.",
    "Sulastri, SKp., M.Kep.",
    "Sulikah,SST.,M.Kes",
    "Supriatin, S.Kep., Ners., M.Kep",
    "Supriatin, S.Kep., Ners., M.Kep.",
    "Suratmi, SST, M. Keb",
    "Suriana, S.Kep.Ns., M.Kep",
    "Suriana, SST., S.Kep.Ns., M.Kep.",
    "Suriani, S.Si., M.Kes.",
    "Surmita, S.Gz., M.Kes.",
    "Suryanti, S.Tr.Keb",
    "Susana Nurtanti, S.Kep., Ns., M.Kes.",
    "Susanti, S.Kep., Ners., M.Kep.",
    "Susanti, SST., Bdn., M.Kes",
    "Susiani Endarwati, S.ST., M.Kes",
    "Susilawati, SST, M.Kes.",
    "Suwanti, S.Kep., Ns., MNS.",
    "Syahrul, SKM., M.Kes",
    "Syaiful, S.Pd., S.Kep., Ns., M.Pd., M.kes.",
    "Syaiful, Skep., Ns., MPd., MKes.",
    "Syisnawati, S.Kep., Ns, M.Kep., Sp.Kep.J",
    "Syukrianti Syahda, SST., M.Kes",
    "Tahan Adrianus Manalu,S.Kep.Ns.,M.Kep.,Sp.Kep.MB",
    "Tioma Naibaho S.Kep., Ns., M.Kep.",
    "Tirza Vivianri Isabela Tabelak, SST., M.Kes.",
    "Titik Agustiyaningsih., S.Kep.Ns., M.Kep",
    "Titik Endarwati, SKM., MPH",
    "Titin Apriyani, S.Tr.Keb., Bdn., M.Tr.Keb.",
    "Tjutju Rumijati, SKp., M.Kep., Sp.Kom",
    "Tonasih, SST., M.Kes.",
    "Toto Harto, M.K.M",
    "Toto Harto, SKM., M.K.M.",
    "Treesia Sujana, S.Kep.,Ners., M.Nurs.",
    "Tri Mulyaningsih, ST., MPH",
    "Tri Wahyuni Ismoyowati., S.Kep., Ns., M.Kep.",
    "Tria Giri Ramdani, S.K.M., M.A.B",
    "Tsuwaibatul Islamiyah, S.Kep., Ns., M.S.",
    "Ucik Ernawati, S.Kep., Ns., M.Kep",
    "Uliyatul Laili, SST., Bdn., M.Keb",
    "Uliyatul Laili, SST., Bdn., M.Keb.",
    "Umu Qonitun, S.ST., M.Keb., M.M.",
    "Uni Afriyanti, Ns., M.Kep",
    "Unziya Khodija, S.ST., M.Gz.",
    "Upus Piatun Khodijah, S.ST., M.Kes.",
    "Utari Yunie Atrie, S.Kep, Ns., M.Kep",
    "Utari Yunie Atrie, S.Kep, Ns., M.Kep.",
    "Utari Yunie Atrie, S.Kep., Ns., M.Kep.",
    "Uun Kurniasih, S.Kep., Ns., M.M.",
    "Vega Muhida, M.Kes",
    "Veronika Toru, S.Kep., Ns., M.Kep",
    "Veryudha Eka Prameswari, SST., M.Kes.",
    "Vika Tri Zelharsandy, S.Tr.Keb., M.Keb.",
    "Vini Yuliani, SST., M.Keb",
    "Vita Maryah Ardiyani, S.Kep., Ns., M.Kep.",
    "Vitaria Wahyu Astuti, S.Kep., Ns., M.Kep",
    "Vivi Dwi Putri, S.ST., M.Kes.",
    "Vonny Khresna Dewi, S.Si.T., M.Kes",
    "Wa Nuliana, S.Kep., Ns., M.Kep",
    "Wa Ode Sri Kamba Wuna, S.ST., M.Keb.",
    "Wahyu Nindi Sayekti, S.ST., M.Keb",
    "Wahyu Nindi Sayekti, S.ST., M.Keb.",
    "Wahyuni, M.Keb.",
    "Wartini Setiawati S.Kep., Ners., M.Kep.",
    "Wasis Widodo, S.Kep., Ners., M.Kep., Sp.Kep.MB.",
    "Wayunah, S.Kp., M.Kep.",
    "Welmince Paulina Nggorong, S.Kep., Ns., M.Kep",
    "Welmince Paulina Nggorong, S.Kep., Ns., М.Kep.",
    "Widanarti Setyaningsih, SKp.MN",
    "Wijayanti, Ns., M.Kep.",
    "Windy Yuliana Budianto, S.Kep., Ns., M.Biomed",
    "Wiralis, S.TP, M.Si.Med",
    "Wita Solama, SST., M.Kes.",
    "Wittin Khairani SPd., MPH",
    "Wiwik Utami, A.PP., S.Pd., M.Kes",
    "Wiwin Priyantari Hn, S.Kep., Ns., M.Kes.",
    "Wiwin Winarsih, S.ST., M.Keb",
    "Wulansari, S.Kep., Ns., M.Kep.",
    "Yaneu Nuraineu, SKM., SST., MKM",
    "Yani Maidelwita, SKM, M.Biomed, PhD",
    "Yanyan Bahtiar, S.Kp., M.Kep.",
    "Yasin Wahyurianto, S.Kep., Ns., M.Si.",
    "Yeli Mardona, M.KM.",
    "Yen Risa Sanputri, S.Tr.Keb., M.Keb., CIMI.",
    "Yenda Hasnita, S.Tr.Keb., M.Keb.",
    "Yeni Yulistanti, S.Kep., Ns., M.Tr.Kep.",
    "Yenni, M.Kep., Ns., Sp.Kep.Kom.",
    "Yeti Yuwansyah, SST., M.Kes., M.Keb",
    "Yogi Catur Putra, MKM.",
    "Yohana Tetty Gultom, S.K.M., M.K.M",
    "Yollanda Dwi Santi Violentina, S.ST., M.Keb",
    "Yos Banne, S.Si., M.Sc., Apt.",
    "Yosefina Nelista, S.Kep., Ns., M.Kep.",
    "Yosephina Maria Hawa Keytimu, S. Kep., Ns., M.P.H.",
    "Yosi yusrotul khasanah, SST.,M.KM",
    "Yuanita Ani Susilowati, M.Kep.Ns.Sp.Kep.Mat",
    "Yuli Ernawati, S.Kep., Ns., M.Kep.",
    "Yuli Widyastuti, S.Kep., Ns., M.Kep.",
    "Yulia Yunara, S.Kep., Ns., M.Kep",
    "Yuliana Dafroyati, S.Kep., Ns, M.Sc.",
    "Yuliana Dafroyati, S.Kep., Ns., M.Sc.",
    "Yuliati.,SKp.,MM.,M.Kep",
    "Yuliyanik, AMd.Keb., S.KM., M.Biomed.",
    "Yuni Kristiani Tumani, S.ST., M.Keb.",
    "Yuni Kurniawati, S.Tr.Keb., M.Keb.",
    "Yuni Retnowati, SST., M.Keb",
    "Yuni Vivi Santri P, SKM., S.Keb., MKM.",
    "Yunita Indah Prasetyaningrum, S.Gz., M.P.H.",
    "Yunita Nazarena, S.Gz., M.Si.",
    "Yupi Supartini, S.Kp., M.Sc.",
    "Yustika Rahmawati Pratami, S.Tr.Keb., M.Keb.",
    "Zakia Asrifah Ramly, S.Pd., M.Si.",
    "Zakiyah, S. Kep., Ners., M.Kep., Sp.Kep.J.",
    "Zeny Fatmawati, SST., MPH",
    "Ziyadatul Chusna Almabruroh Yuni Alfi, S.ST, M.KM.",
    "Zurni Nurman , S.ST, M.Biomed"
];

type optionProps = {
    value: string;
    label: string;
}
interface FilterBookProps {
    onUpdateParams: (params: URLSearchParams) => void;
}
const FilterBook: React.FC<FilterBookProps> = ({ onUpdateParams }) => {
    const router = useRouter();
    const pathname = usePathname();
    const queries = useSearchParams();
    const [search, setSearch] = useState<string>("");
    const [catagoriesData, setCatagoryData] = useState<optionProps[]>([]);
    const [category, setCategory] = useState<optionProps | null>(null);
    const [authorsData, setAuthorsData] = useState<optionProps[]>([]);
    const [author, setAuthor] = useState<optionProps | null>(null);

    useEffect(() => {
        const params = new URLSearchParams(Array.from(queries.entries()));
        const addQueryParam = () => {

            if (search !== '') {
                params.set("q", search);
                onUpdateParams(params);
            } else {
                params.delete("q");
                onUpdateParams(params);
            }
            if (category) {
                params.set("category", category.value)
                onUpdateParams(params);
            } else {
                params.delete("category");
                onUpdateParams(params);
            }
            if (author) {
                params.set("author", author.value);
                onUpdateParams(params);
            } else {
                params.delete("author");
                onUpdateParams(params);
            }
            router.push(`${pathname}?${params.toString()}`);


        };
        async function getCatagoryData() {
            const categoriesData: optionProps[] = [];
            const response = await fetch('http://127.0.0.1:8000/api/v1/category');
            const data = await response.json();
            data.data.map((catagory: any) => {
                categoriesData.push({
                    value: catagory.slug,
                    label: catagory.category
                });
            });
            setCatagoryData(categoriesData);
        }
        async function getAutorsData() {
            const authorsData: optionProps[] = [];

            const response = await fetch('http://127.0.0.1:8000/api/v1/author');
            const data = await response.json();
            if(!isEmpty(data.data)){
                data.data.map((author: any) => {
                    authorsData.push({
                        value: author.slug,
                        label: author.author_name + ", " + author.author_title
                    });
                });
                setAuthorsData(authorsData);
            }
        }
        getCatagoryData();
        getAutorsData();
        addQueryParam();
    }, [author, category, onUpdateParams, pathname, queries, router, search]);

    return (<>

        <div className="w-78 px-4 hidden md:block">
            <h2 className='text-xl font-bold text-[var(--primary)] mb-8'>Filter</h2>
            <SearchBook search={search} setSearch={setSearch} />
            <div className="mb-4">
                <label htmlFor="category" className="block text-sm font-medium text-gray-700">
                    Kategori
                </label>
                <SelectOption
                    isClearable={true}
                    options={catagoriesData}
                    value={category}
                    onChange={(e) => setCategory(e as optionProps | null)}
                    className="react-select-input"
                    id="category"
                    name="category"
                />
            </div>
            <div className="mb-4">
                <label htmlFor="author" className="block text-sm font-medium text-gray-700">
                    Penulis
                </label>
                <SelectOption
                    isClearable={true}
                    options={authorsData}
                    value={author}
                    onChange={(e) => setAuthor(e as optionProps | null)}
                    className="react-select-input"
                    id="author"
                    name="author"
                />
            </div>
        </div>

    </>);
}

export { FilterBook };